### ISSUE TITLE
AIND-ISOLATION tries to compare IsolationPlayer objects with Agent objects

### ISSUE THREAD

**Issue by olivergraeser** [udacity/aind-issue-reports#99] opened 2017-05-30 23:11 UTC
https://github.com/udacity/AIND-Isolation/blob/master/isolation/isolation.py#L337 and https://github.com/udacity/AIND-Isolation/blob/master/tournament.py#L63 show that `winner` is of type `IsolationPlayer`. `test_agents`, meanwhile, are of type `Agent` (see https://github.com/udacity/AIND-Isolation/blob/master/tournament.py#L133). However, the algorithm tries to find players in the agent list (`winner not in test_agents`, https://github.com/udacity/AIND-Isolation/blob/master/tournament.py#L68), which will always fail, and therefore blame forfeits of the CPU agents on the test_agents.

**Comment by cgearhart** [comment] 2017-06-05 17:00
Nice catch. It's actually working as intended; however the first condition is pointless and will be removed. When running the tournament, your code is used for all of the agents -- so it doesn't matter whether it's a "CPU" agent or a test agent that fails: both cases indicate an unhandled edge case in student code. (Fixed in commit #b8937c44)

**Closed as completed by cgearhart** 2017-06-05 17:00 UTC

**Comment by olivergraeser** [comment] 2017-06-06 02:44
If this behaviour is indeed the desired one then at least also the error message should be changed since right now it reports that _your_ agents are forfeiting games, i.e., the Alphabeta agents (since tournament.py only pitches the student's alphabeta models against computer model which include minimax). Since the typical problem leading to forfeits (a `>` rather than a `>=` in the score comparison) is separately implemented, this message can tell the students that there is a bug in AlphaBeta while in reality, AlphaBeta doesnt forfeit anything and only MiniMax does.
